const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
const { tentarComando } = await import("@/lib/kiah-comandos.server");
const uid = "043de90d-bf75-4a7e-ae04-cc1b1cb0edd1";
const mk = async (d: string) => {
  const { data, error } = await supabaseAdmin.from("tarefas").insert({ user_id: uid, descricao_limpa: d, confirmado: true }).select("id").single();
  if (error) throw error; return data.id as string;
};
const a = await mk("TESTE validacao feito");
const b = await mk("TESTE validacao deletar");
const c = await mk("TESTE validacao adiar");
console.log("feito:", await tentarComando("feito " + a.slice(0,6), uid));
console.log("deletar:", await tentarComando("deletar " + b.slice(0,6), uid));
console.log("adiar:", await tentarComando("adiar " + c.slice(0,6) + " 30", uid));
console.log("silenciar:", await tentarComando("silenciar " + c.slice(0,6), uid));
console.log("sem id:", await tentarComando("feito", uid));
const { data } = await supabaseAdmin.from("tarefas").select("id,status,prazo_estimado,silenciada_ate").in("id",[a,b,c]);
console.log(data);
await supabaseAdmin.from("kiah_envios_log").delete().in("tarefa_id",[a,b,c]);
await supabaseAdmin.from("tarefas").delete().in("id",[a,b,c]);
const { count } = await supabaseAdmin.from("tarefas").select("id",{count:"exact",head:true}).like("descricao_limpa","TESTE validacao%");
console.log("restos de teste:", count);
